- name: add node repo key
  apt_key:
    url: "{{ node_repo_key }}"
    state: present

- name: add node repo
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ dist_name }} main"

- name: install node
  apt:
    pkg: nodejs
    state: present

